### ISSUE TITLE
Documentation for single.php, page.php, archive.php, etc. as controllers

### ISSUE THREAD

**Issue by karenkitchens** [forumone/gesso-wp#19]

**Comment by treb0r** [comment]
Some more docs would be great.

**Comment by elvismdev** [comment]
Sure @treb0r! We are looking forward to add those pretty soon.

Currently on [single.php](https://github.com/forumone/gesso-wp/blob/master/single.php), [page.php](https://github.com/forumone/gesso-wp/blob/master/page.php) and [archive.php](https://github.com/forumone/gesso-wp/blob/master/archive.php) there is the initial code as the generic starting point. 

Since this theme depends on the [Timber Library](https://wordpress.org/plugins/timber-library/), a good place to start building up some queries and `.twig` template files for posts and pages would be their own documentation at http://timber.github.io/timber/

Eventually, we will be adding a wiki with our own recipes as well  :)

**Comment by treb0r** [comment]
How should I include my UI patterns from pattern lab in my theme templates?

**Comment by dmoon79** [comment]
@treb0r right now there is no direct link between your Patternlab and Wordpress's theme templates.  I typically just copy the HTML code from my Patternlab UI template, directly into a Wordpress template, then replace any Twig variables in the new template.  Since Patternlab and Wordpress don't share the same backend.

**Comment by treb0r** [comment]
Thanks, makes sense.

The holy grail would be to have a seamless integration of the two. I wonder if it might be possible to come up with twig variables that could work in either context.
