### ISSUE TITLE
2.x - integrating grunt into Pattern Lab appears incomplete?

### ISSUE THREAD

**Issue by gergisKhan** [forumone/gesso-wp#75]
When using grunt to run the GessoBuild tasks, the css and js directories are created in the theme root. They are not copied to Pattern Lab.

Is this normal? "Running php core/console --server" does bring up  the Pattern Lab but it does not appear that any styling is accessible in this fashion.

Is there a missing step in the workflow, or am I potentially misusing this theme?

**Comment by coreylafferty** [comment]
@gergisKhan once you run grunt or grunt gessoBuild, that should compile the Sass and Pattern Lab files.  You can access Pattern Lab by opening the index.html file in the /public directory in your browser from your local site (e.g., http://localhost/wp-content/themes/gesso/pattern-lab/public/index.html) or just open the file in the browser directly from the file system.

Gesso is setup so that the theme and Pattern Lab reference the same JS and CSS files to avoid duplication.  Changes to the Sass will be reflected both in WordPress and in Pattern Lab.  If you look in /pattern-lab/source/_meta/_00-head.twig  and _01-foot.twig, you can see where it's importing the CSS and JS from the theme root.

Let me know if that helps or if you have any other questions.

**Comment by gergisKhan** [comment]
I think I understand my confusion! So, one should NOT run php core/console --server to view the PatternLab -- just view it DIRECTLY via the link above?

That probably ends up solving just about everything I was having trouble with.
